# Generated by Django 4.0.2 on 2022-03-15 08:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('user_mail', models.EmailField(blank=True, max_length=150)),
                ('salt_value', models.CharField(max_length=500)),
                ('user_pass', models.CharField(max_length=500)),
                ('is_admin', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.departments')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.authlevel')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200)),
                ('occurred_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.users')),
            ],
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=50, unique=True)),
                ('name_of_complainant', models.CharField(default='Anonymous', max_length=25)),
                ('incident_type', models.CharField(max_length=25)),
                ('location', models.CharField(blank=True, max_length=25)),
                ('description', models.TextField(max_length=1000)),
                ('gender', models.CharField(max_length=10)),
                ('subcounty', models.CharField(blank=True, default='Not Specified', max_length=20)),
                ('wards', models.CharField(blank=True, max_length=25)),
                ('email_of_complainant', models.CharField(blank=True, max_length=50)),
                ('phone_no', models.CharField(blank=True, max_length=15)),
                ('incident_report_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('incident_occurrence_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('due_on', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ManyToManyField(to='incidents.Users')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.departments')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.incidentstatus')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=1000)),
                ('date_of_reply', models.DateTimeField(default=django.utils.timezone.now)),
                ('incident', models.ManyToManyField(to='incidents.Incidents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.users')),
            ],
        ),
    ]
