# Generated by Django 4.0.2 on 2022-03-15 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='user',
            new_name='performed_by',
        ),
    ]
